[package]
name = "rust_games_games"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_games_shared = {path = "../shared"}
dfdx = "0.13.0"
